"""This file is auto-generated. Do not edit manually."""

from typing import TypedDict, Optional, List, Literal


class SubscriptionUpdate(TypedDict, total=False):
    """Plan ID associated with the subscription."""
    plan_id: Optional[str]
    """Payment collection method for invoices generated by the subscription."""
    collection_method: Optional[Literal["manual", "automatic"]]
    """Proration mode for the subscription."""
    proration_mode: Optional[Literal["none", "invoice_immediately", "invoice_later"]]
    """Payment method ID associated with the subscription. Required if collection_method is `automatic`."""
    payment_method_id: Optional[str]
    """Billing cycle type of the subscription."""
    billing_cycle_type: Optional[Literal["anniversary", "calendar"]]
    """Modify fee quantities for the subscription plans and fees."""
    items: Optional[List[dict]]
